# Generated by Django 4.2.2 on 2023-07-22 07:28

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=project.models.getFileName
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show, 1-hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vendor", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=project.models.getFileName
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("old_price", models.IntegerField()),
                ("new_price", models.IntegerField()),
                ("description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show, 1-hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default, 1-trending"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.catagory",
                    ),
                ),
            ],
        ),
    ]
